### ISSUE TITLE
Startup server bug on Unix

### ISSUE THREAD

**Issue by adammcarth** [MarshallOfSound/OpenLog#1]
There's a directory bug when starting up the server from the root of OpenLog (example used in the documentation). I receive the following error when running `node server/server.js`:

``` bash
Error: ENOENT, no such file or directory '../config.inc.json'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.<anonymous> (/Users/<user>/Downloads/OpenLog-0.1.0/server/server.js:8:28)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
```

I'm not sure if perhaps the windows NFC filesystem behaviour is slightly different with node, but at least on my unix based development system which is running OSX 10.10. Don't forget the importance of using the _module-level_ `__dirname` node variable available to you - it's not your place to assume a script will always be run from a specific directory :)

**Comment by MarshallOfSound** [comment]
Fixed in latest master

**Comment by adammcarth** [comment]
Please review my PR, contains a better fix.
